### ISSUE TITLE
Faraday dependency

### ISSUE THREAD

**Issue by brendonlow** [instructure/footrest#1]
The dependency on faraday 0.8.7 caused some issues with my code base the other day. (footrest/footrest.gemspec:26) Wondering if there was any specific reason for this or if it could be updated to be a little more flexible? Probably just a relic due to the last update being in 2013.

**Comment by simonista** [comment]
Yeah, we can definitely make that more lenient. I'll push something up.

**Comment by simonista** [comment]
Just a quick update, I've got a commit ready internally to make this change, but the owner of the repo has been working on a huge deadline that was today. Hoping they'll have time to look at it this week.

**Comment by simonista** [comment]
Fixed in a908906eb942257185beb40299c660f2695ca973
